### ISSUE TITLE
Cant open links with Librewolf

### ISSUE THREAD

**Issue by Saroufim** [flathub/io.gitlab.librewolf-community#2]
Once it is set as the default browser, clicking on "open link" in another app fails to open a new tab with the link. It either says Librewolf is already running or it just opens the browser.

**Comment by lsfxz** [comment]
I've observed something like this before with Firefox on Wayland.

Assuming you're on Wayland, you could try overriding the .desktop file by creating `~/.local/share/applications/io.gitlab.librewolf-community.desktop` with the following modified content (from the file from the flatpak package):

```
[Desktop Entry]
Name=LibreWolf
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=librewolf --file-forwarding io.gitlab.librewolf-community @@u %u @@
Icon=io.gitlab.librewolf-community
Type=Application
MimeType=text/html;text/xml;application/xhtml+xml;x-scheme-handler/http;x-scheme-handler/https;application/x-xpinstall;application/pdf;application/json;
StartupWMClass=LibreWolf
Categories=Network;WebBrowser;
StartupNotify=true
Terminal=false
X-MultipleArgs=false
Keywords=Internet;WWW;Browser;Web;Explorer;
Actions=new-window;new-private-window;profilemanager;
X-Flatpak=io.gitlab.librewolf-community

[Desktop Action new-window]
Name=Open a New Window
Exec=/usr/bin/flatpak run --env=GDK_BACKEND=wayland --branch=stable --arch=x86_64 --command=librewolf --file-forwarding io.gitlab.librewolf-community @@u %u @@

[Desktop Action new-private-window]
Name=Open a New Private Window
Exec=/usr/bin/flatpak run --env=GDK_BACKEND=wayland --branch=stable --arch=x86_64 --command=librewolf --file-forwarding io.gitlab.librewolf-community --private-window @@u %u @@

[Desktop Action profilemanager]
Name=Open the Profile Manager
Exec=/usr/bin/flatpak run --env=GDK_BACKEND=wayland --branch=stable --arch=x86_64 --command=librewolf --file-forwarding io.gitlab.librewolf-community --ProfileManager @@u %u @@
```

(or if you're running it directly via `flatpak run  --env=GDK_BACKEND=wayland ...`).

There's been an explanation for this behaviour somewhere, I just don't have it at hand right now.

You usually don't want to set `GDK_BACKEND=wayland` everywhere else as some apps will fail with it (notably some older / non-ozone electron apps), and it can't be set for everyone in the flatpak release by default, because not everyone's using wayland.

If there's a better way around this, I'm all ears :)

**Comment by Saroufim** [comment]
This solved it indeed. Thanks a bunch.

**Comment by lsfxz** [comment]
I've just added a proposal to the FAQ concerning this issue (and how to fix it), which should be live with the next regular release.

Thanks for bringing it up! :)

**Comment by lsfxz** [comment]
Just as a followup to this: it seems that the "cleaner" solution to this would be to instead set `MOZ_DBUS_REMOTE=1` everywhere (ie. in the `.desktop` file as well as in your environment "everywhere").

See https://wiki.archlinux.org/title/Firefox#Applications_on_Wayland_can_not_launch_Firefox and https://bugzilla.mozilla.org/show_bug.cgi?id=1508803#c18. I'll reopen this for now just to remind me to update the FAQ wit it :)

**Comment by Paveloom** [comment]
Solutions above don't seem to work on my end. See another report [here](https://gitlab.com/librewolf-community/browser/flatpak/-/issues/11).

**Comment by Vite** [comment]
Experiencing same error as @Paveloom on freshly installed elementaryOS 6

**Comment by Paveloom** [comment]
See [linux#256 (comment 740596927)](https://gitlab.com/librewolf-community/browser/linux/-/issues/256#note_740596927) for solution.

**Comment by lsfxz** [comment]
With Mozilla having dropped the `MOZ_DBUS_REMOTE` stuff and instead using d-bus as default if the running environment suggests it (and it's enabled during building it), this should "just work" nowadays.

A fix for the new issues with that was commited with 59fa1a92b52928eb8fb88dc293c480ba9d4b3b62, more details are also available in https://gitlab.com/librewolf-community/browser/flatpak/-/issues/13#note_814715875.

**Comment by elvybean** [comment]
Since installing Librewolf via Flatpak I was unable to open links from Obsidian (.deb), I used the fix recommended `flatpak override --user --env=GDK_BACKEND=wayland io.gitlab.librewolf-community` and this resolved my problem. 

Thought I'd comment here anyway since the issue was closed and was presumed to just work now.
